reuixiy/hugo-theme-meme

- layouts/partials/third-party/valine.html
将Valine的CDN换为jsdelivr以获得更加优异的加载速度。
Jsdelivr在中国也有CDN节点，真正做到了全球加速，而且同时为github、npm、wordpress提供静态资源加速，而valine正是发布在npm上的。在我亲自试过之后，认为jsdelivr的访问速度是最佳的。
> Change the Valine cdn to jsdelivr

- i18n/de.toml
- i18n/en.toml
- i18n/pt-br.toml
- i18n/zh.toml
- layouts/404.html
Hi!
First of all, congratulations for this cool Hugo theme.
I've submitted the Brazilian Portuguese translations. I also have translated the comments inside the file.
> Add Brazilian Portuguese translations

- layouts/partials/components/post-meta.html
The custom template only needs the page itself as context, it can read out `.isHome` itself if necessary - this makes things simpler.
> Fixes #136 - Allow customization of post metadata

- layouts/_default/list.html
- layouts/partials/pages/taxonomy.html
- layouts/partials/utils/list-item.html
I made the `list-item.html` template emit the `ul` tag rather than its callers. This has an added bonus: no `<ul>` tag is being emitted now if `limitEntriesLimit` is set to `0` (previously an empty one would be created).
> Fixes #151 - Move headings out of <ul> tag

- layouts/index.sectionsatom.xml
- layouts/index.sectionsrss.xml
- layouts/partials/components/post-copyright.html
- layouts/partials/components/post-share.html
- layouts/partials/footer.html
- layouts/partials/head.html
- layouts/partials/pages/home-poetry.html
- layouts/partials/pages/post.html
- layouts/partials/pages/tree-sections.html
- layouts/partials/third-party/disqus.html
- layouts/partials/third-party/service-worker.html
- layouts/partials/utils/author.html
- layouts/partials/utils/auto-detect-images.html
- layouts/partials/utils/content.html
- layouts/partials/utils/data-attributes.html
- layouts/partials/utils/date.html
- layouts/partials/utils/images.html
- layouts/partials/utils/json-ld.html
- layouts/partials/utils/markdownify.html
- layouts/partials/utils/open-graph.html
- layouts/partials/utils/relative-url.html
- layouts/partials/utils/title.html
- layouts/partials/utils/toc.html
- layouts/partials/utils/tree-sections.html
- layouts/partials/utils/twitter-cards.html
The initial commit fixes #137. I also could fail to notice that `hrefTargetBlank` processing in `markdownify.html` seems very inefficient - let me know if I missed something that the original code was doing better.
I must say that I didn't test the changes to `content.html` fully - it's way too many branches and settings. But the changes are pretty straightforward.
I want to add more commits to this pull request, there are other templates following the same pattern.
> Make templates return results properly instead of abusing .Scratch

- assets/js/header.js
- assets/scss/layout/_header.scss
This implements the work-around described in #146. Since the header height has to be known, this will do an approximate calculation of the header height in CSS (already works well enough for me under most circumstances). The header will then be measured precisely by JavaScript if enabled.
> fix: When scrolling to an anchor, account for the header height (fixes #146)

- layouts/partials/components/post-share.html
- layouts/partials/head.html
There is a remaining `safeJS` call in `partials/third-party/valine.html`. The documentation is lacking but judging by the default value this one is actually required - the value here really can be a JavaScript expression.
> fix: Remove unnecessary safeJS/safeURL calls

- assets/js/copy.js
- assets/js/wrap-table.js
- layouts/partials/script.html
- layouts/partials/utils/content.html
`innerHTML`/`outerHTML` usage generally raises security flags, these are common sources of XSS vulnerabilities. Even through `outerHTML` usage in MemE is easily identified as unproblematic, its performance is still suboptimal (DOM tree has to be serialized to HTML code and parsed back again) and it could cause further issues if JavaScript code attaches some state (e.g. event handlers) to elements which are being thrown away and replaced.
For table wrapping, JavaScript is completely unnecessary - this replacement can be done at generation time.
Things are somewhat more complicated with the copy buttons. Since only top-level `<pre>` tags need to be wrapped, it's hard to achieve this when the page is generated. So my code is doing proper DOM manipulation. Note that `style="position: …
> refactor: Do not rely on HTML code manipulation in JavaScript

- assets/js/nav-toggle.js
This *might* be the reason why theme switcher was reported to be broken (https://github.com/reuixiy/hugo-theme-meme/issues/181#issuecomment-635374813). In my testing this error didn't affect any unrelated functionality however.
> fix: Safari doesn't support addEventListener on media queries

- README.md
- README.zh-cn.md
This changes the English README file, I cannot change the Chinese one.
> docs: Document browser requirements (fixes #181)

- layouts/index.sectionsatom.xml
- layouts/index.sectionsrss.xml
- layouts/partials/components/post-nav.html
- layouts/partials/components/post-share.html
- layouts/partials/components/related-posts.html
- layouts/partials/head.html
- layouts/partials/pages/home-posts.html
- layouts/partials/pages/post.html
- layouts/partials/pages/tree-categories.html
- layouts/partials/pages/tree-sections.html
- layouts/partials/third-party/disqus.html
- layouts/partials/utils/json-ld.html
- layouts/partials/utils/list-item.html
- layouts/partials/utils/open-graph.html
- layouts/partials/utils/title.html
This is my approach to use markdownified titles. Implements #179 
Not sure if this is the best way to do it, or if there is a more central place to apply markdownify just once?
> First approach to markdownify title

- layouts/index.searchindex.json
- layouts/partials/utils/title.html
As mentioned in https://github.com/reuixiy/hugo-theme-meme/pull/183#discussion_r433662953, I renamed the variables to make the logic more clear. I also fixed the title for taxonomy pages (#183 introduced a bug, making it "security: security" instead of "Categories: security") and removed unnecessary code (massaging the title for regular pages no longer necessary).
Finally, I added a "BREAKING CHANGE" note to this commit because #183 didn't. I checked the output for my blog, there are lots of changes, mostly due to the typographer extension now doing its job on the titles. In my case these changes all seem unproblematic.
> refactor: Make title.html partial more readable, fix title for taxonomy pages

- layouts/index.searchindex.json
- layouts/index.sectionsatom.xml
- layouts/index.sectionsrss.xml
- layouts/partials/components/post-share.html
- layouts/partials/head.html
- layouts/partials/utils/json-ld.html
I noticed an issue when a description is deduced from a post starting with something like `It's a nice weather outside.` The typographer Goldmark extension turns this into `It&rsquo;s a nice weather outside.` and I see this entity escaped twice in the meta tag then. It seems that `| plainify` should always be applied in connection with `| htmlUnescape`.
> fix: Avoid double escaping when using post description

- layouts/index.searchindex.json
I noticed that only including regular pages in the search index isn't a good idea - I have pages like "privacy policy" which are actually sections. So now any page with content is included.
> fix: Search index should include sections & co. if these have content

- layouts/partials/components/post-copyright.html
- layouts/partials/components/post-meta.html
- layouts/partials/pages/home-posts.html
- layouts/partials/pages/post.html
This adds a bunch of class names according to the [h-entry spec](http://microformats.org/wiki/h-entry). It allows the contents to be parsed semantically by microformats parser, e.g. https://python.microformats.io/. This is useful for example for [Webmention receivers](https://www.w3.org/TR/webmention/) – these prefer to have useful data about a page rather than merely its URL.
The significant missing part here is `p-author`, MemE simply doesn't display an author for each post.
> feat: Adjust post markup to conform to h-entry spec

- config-examples/en/config.toml
- layouts/partials/script.html
- layouts/partials/style.html
I noticed that neither scripts nor styles of my websites were loading when somebody attempted to translate an article via Google Translate. That's due to `enableFingerprint = true` configuration option - it doesn't merely enable fingerprinting but also Subresource Integrity. Turns out, cross-origin requests with `integrity` attribute are blocked by default, otherwise these could be [misused to leak information](https://bugs.chromium.org/p/chromium/issues/detail?id=812667).
The solution consists of two parts:
1. Add `crossorigin="anonymous"` attribute to the requests in question (done here).
2. Add `Access-Control-Allow-Origin: *` header to JS/CSS requests - has to be done in server configuration.
The second part probably needs documenting. The other option would be to separate …
> fix: Allow scripts and styles to load cross-origin, e.g. from Google Translate

- layouts/partials/third-party/lunr-search.html
when
```toml
defaultContentLanguage = "ja"
```
lunr is not working since lunr.ja.min.js raises an error.
lunr.ja.min.js requires tinyseg.js.
https://github.com/MihaiValentin/lunr-languages/blob/master/demos/demo-browser-require-ja.html#L11
> fix: add tinyseg.js to scripts if japanese

- static/manifest.json
I found the current `manifest.json` missed the requirement of `Fast and reliable` in PWA.
You can get more information in this [link](https://web.dev/works-offline/)
And here is the report of `io-oi.me` with [manifest.json](https://io-oi.me/manifest.json)
I used this [manifest.json](https://www.zhangjc.site/manifest.json) and it meets this requirement.
Also, for those whose homepage is not hosted on the root path, one can refer to this [link](https://www.coder.work/article/938443) to work with the `scope` parameter.
> [Update] Modify start_url to meet the PWA's fast and reliable requirment

- config-examples/en/config.toml
- config-examples/zh-cn/config.toml
- config-examples/zh-tw/config.toml
- i18n/ru.toml
- layouts/partials/head.html
- layouts/partials/third-party/yandex-metrika.html
[Yandex.Metrika](https://metrika.yandex.ru/) is a popular analytics tracking tool (similar to Google Analytics). The code in this PR adds support for the Yandex.Metrika by installing corresponding `<script>` code in the `<head>` section (and only in the production environment).
To configure the Yandex.Metrika counter, please specify `yandexMetrikaId` parameter with you y.metrika Id in your config.toml.
> Add support for Yandex.Metrika

- layouts/partials/third-party/medium-zoom.html
For example, I don't want to use medium-zoom when I write an img tag directly under the a tag in markdown, as shown below.
```md
<a href="https://gohugo.io/">
</a>
```
> Exclude  medium-zoom for img tags directly under a tag

- layouts/partials/utils/content.html
```
// text
xxx
xxx
// before
Xxx
Xxx
// after
Xxx
xxx
```
> fix: drop cap to the identical paras only once

- assets/scss/layout/_header.scss
change header width from 100% to 100vw in order to avoid difference resulted by scroll bar.
Resolves [#350](https://github.com/reuixiy/hugo-theme-meme/issues/350)
> fix: make header width to 100vw to avoid change when scroll bar appears

- layouts/partials/utils/content.html
- layouts/partials/utils/images.html
Enable both
```toml
imageHostURL = "https://example.com"
```
```toml
imageHostURL = "https://example.com/"
```
> fix: ignore suffix slash of image host

- assets/scss/themes/_light.scss
when defaultTheme is dark, images won't change to 100% contrast when toggled to light mode (#365)
> fix(scss): solve issue #365

- layouts/partials/third-party/disqus.html
- layouts/partials/third-party/gitalk.html
- layouts/partials/third-party/utterances.html
- layouts/partials/third-party/valine.html
Check if the relevant container exists before loading comments to avoid uncaught errors being thrown when loading. For example, pages without comments will throw `Uncaught Error: Container not found, window.document.getElementById: gitalk-container` when using Gitalk.
> fix: check before loading comments

- layouts/partials/third-party/lunr-search.html
While I was using this theme with the (pt-br)[https://github.com/reuixiy/hugo-theme-meme/blob/master/i18n/pt-br.toml] language, I noticed this warning:
```
WARN 2022/07/21 21:03:09 The site language "pt-br" isn't supported by lunr, the search results might be suboptimal. Supported languages are: ["ar" "da" "de" "du" "es" "fi" "fr" "hu" "it" "ja" "nl" "no" "pt" "ro" "ru" "sv" "tr" "vi"]
```
So I removed the country code (-br) from the validation and now the warning doesn't show anymore.
> Remove country code on lunr language validation

- layouts/partials/utils/content.html
I try to write the following markdown:
```markdown
```
And find that the image url was replaced with `imageHostURL/https://path.to.img`.
> fix: image and video host

- config-examples/en/config.toml
- config-examples/zh-cn/config.toml
- config-examples/zh-tw/config.toml
- layouts/partials/third-party/google-adsense-unit.html
Currently Google Adsense Unit Ads support many kinds of ads. I adjust the partial file to support as most 3 kinds of ads including autofit(same as before), in article and auto relaxed.
Maybe it's too many ads in my blog enough..
> Improve google adsense for units display

- assets/scss/main.scss
- config-examples/en/config.toml
- config-examples/zh-cn/config.toml
- config-examples/zh-tw/config.toml
- layouts/partials/components/fedishare.html
- layouts/partials/components/post-share.html
BREAKING CHANGE: options like shareOnFacebook or shareViaQRCode have been replaced by postShareItems option
> feat: Allow setting the order of share items via postShareItems option (fixes #446)

- README.md
- config-examples/en/config.toml
- config-examples/zh-cn/config.toml
- config-examples/zh-tw/config.toml
- layouts/partials/utils/author.html
- layouts/partials/utils/open-graph.html
See https://rknight.me/blog/highlighting-journalism-with-the-fediverse-creator-tag/ on information about the Fediverse Creator tag. It’s pretty new, Mastodon (and likely other applications as well soon) now supports linking to the Fediverse user who authored the article.
> feat: Support fediverse:creator OpenGraph tag

- layouts/partials/components/post-nav.html
@reuixiy  `.Page.PrevPage` and `.Page.NextPage` were deprecated in Hugo v0.123.0 and have been removed in Hugo 0.141.0.
Use .Page.Prev instead.
> fix removed variables
